language: java
jdk:
- openjdk8
sudo: enabled
services:
- mysql
before_install:
- sudo mysql -e 'DROP DATABASE IF EXISTS bug_db;'
- sudo mysql -e 'CREATE DATABASE bug_db;'
- sudo mysql -e 'USE bug_db;'
- sudo mysql < "bug_db.sql"
script: mvn clean verify
